### ISSUE TITLE
EmberPlus - Typescript library

### ISSUE THREAD

**Issue by yboujraf** [olzzon/sisyfos-audio-controller#104]
Dear @olzzon 

Do you have developed the emberPlus library in Typescript  or you converted javascript library to typescript?

Are you using only Qualifiednode and Qualifiedparameters or more ?

Best Regards,
Youssef

**Comment by olzzon** [comment]
Hi Yboujraf,

We've sort of parked the Ember support until a faster lib has been made.
I converted the EVS/NRK eve module to TypeScript this summer, but parked it when we concluded that the current Nodejs module isn't fast enough.

**Comment by olzzon** [comment]
So right now we focus on 
SSL, Midas/Behringer, CasparCG, and Ardour (for software only mixing)

**Comment by yboujraf** [comment]
Dear @olzzon 

thanks for the feedback.

I am following what you are doing it is great.

I 'd like to use you UI for other purpose, could you share in which folder we have the fader layout ?

Best Regards
Youssef

**Comment by olzzon** [comment]
If you go to feat/nodejs branch - the GUI has been separated (in src) from the server.

**Comment by olzzon** [comment]
I think that would be the easiest way to isolate it.

**Comment by olzzon** [comment]
Closing this now.
If you have questions please go to:
https://sofietv.slack.com/archives/CK54934BY 
#sofie channel
